api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false

    # The title of the API.
    title: 'API - I need'

    # The description of the API.
    description: 'Bienvenue sur la documentation. Ici ce trouve tous les points d entrés à l API.<br>
    Pour accéder au back-office "/login"'

    # The version of the API.
    version: '1.1.0'
